Added motr service start & stop functions
Signed-off-by: Rohan Dhodare <rohan.v.dhodare@seagate.com>

diff --git a/st/initscripts b/st/initscripts
--- a/st/initscripts
+++ b/st/initscripts
@@ -18,7 +18,8 @@
 # please email opensource@seagate.com or cortx-questions@seagate.com.
 #
 
-set -e
+#set -x
+#set -e
 
 #
 # Wrapper script for Jenkins test '03initscript-tests'
@@ -27,53 +28,61 @@ set -e
 M0_SRC_DIR=`readlink -f $0`
 M0_SRC_DIR=${M0_SRC_DIR%/*/*}
 
-currdir=$(pwd)
-SANITY_SANDBOX_DIR="/var/motr/sanity_$timestamp"
-. $M0_SRC_DIR/utils/functions # report_and_exit
+
+echo $M0_SRC_DIR
+m0t1fs_dir="$M0_SRC_DIR/m0t1fs/linux_kernel/st"
+. $m0t1fs_dir/common.sh
+. $m0t1fs_dir/m0t1fs_common_inc.sh
+. $m0t1fs_dir/m0t1fs_client_inc.sh
+. $m0t1fs_dir/m0t1fs_server_inc.sh
 
 cd $M0_SRC_DIR
-start_singlenode()
+
+N=$1
+K=$2
+S=$3
+P=$4
+stride=$32
+
+motr_service_start()
 {
-	mkdir -p "$SANITY_SANDBOX_DIR"
-	cd "$SANITY_SANDBOX_DIR"
+	local n=$1
+	local k=$2
+	local s=$3
+	local p=$4
+	local stride=$5
+	local multiple_pools=0
 
-	# setup motr singlenode
-	$M0_SRC_DIR/utils/m0singlenode activate
-	$M0_SRC_DIR/utils/m0setup -cv -d "$SANITY_SANDBOX_DIR" -m "$SANITY_SANDBOX_DIR"
-	$M0_SRC_DIR/utils/m0setup -N 1 -K 0 -S 0 -P 8 -s 8 -Mv -d "$SANITY_SANDBOX_DIR" \
-		-m "$SANITY_SANDBOX_DIR" --no-m0t1fs
+	echo "n k s p:$N $K $S $P"
+	motr_service start $multiple_pools $stride $n $k $s $p
+	if [ $? -ne 0 ]
+	then
+		echo "Failed to start Motr Service..."
+		return 1
+	fi
+	echo "motr service started"
 
-	# start motr
-	$M0_SRC_DIR/utils/m0singlenode start
+	ios_eps=""
+	for ((i=0; i < ${#IOSEP[*]}; i++)) ; do
+		ios_eps="$ios_eps -S ${lnet_nid}:${IOSEP[$i]}"
+	done
+	return 0
 }
 
-stop_singlenode()
+motr_service_stop()
 {
-	# stop motr
-	$M0_SRC_DIR/utils/m0singlenode stop
-	$M0_SRC_DIR/utils/m0setup -cv -d "$SANITY_SANDBOX_DIR" -m "$SANITY_SANDBOX_DIR"
-	cd "$currdir"
-
-	# cleanup remaining motr-services
-	systemctl start motr-cleanup
-
-	# remove sanity test sandbox directory
-	if [[ "$1" == "cleanup" ]]
+	motr_service stop
+	if [ $? -ne 0 ]
 	then
-		rm -rf "$SANITY_SANDBOX_DIR"
+		echo "Failed to stop Motr Service..."
+		return 1
 	fi
 }
-sudo ./scripts/install-motr-service -u
-sudo ./scripts/install-motr-service -l
 
-start_singlenode
-echo "=================================================="
-echo "========Motr singlenode services started=========="
-echo "=================================================="
-stop_singlenode "cleanup"
-echo "=================================================="
-echo "========Motr singlenode services stopped=========="
-echo "=================================================="
+motr_service_start $N $K $S $P $stride 
+echo "CORTX- Motr Service is started"
+motr_service_stop
+echo "CORTX- Motr Service is stopped"
 
 
 report_and_exit initscripts $?
