EOS-13890 m0reportbug: Removed halon related things and fixed warn/error logs
* In last version update there was version mismatch, corrected that.

* Updated correct name of libgalois. libgalois  library name itself
  contains version name (libgalois-0.1.so) updated actual name in
  path_rpm() and path_src()

* Redirected error logs (journalctl) into REPORT file so that it
  won't reflect on terminal but can be seen in report summary.

* Removed the collection of kernel buffer, because we have lack of
  debugfs support.

* Removed logs/binary collection related to halon since we are not using
  it. Also removed collection of m0traces of s3server and hax as it will
  be collected into respective component support bundle.

* Added 'df -h' to probe info.

* Bumped up version by 2 (since it was missed in last commit)

diff --git a/utils/m0reportbug b/utils/m0reportbug
--- a/utils/m0reportbug
+++ b/utils/m0reportbug
@@ -101,6 +101,14 @@ main() {
                 warn "$IN_DIR: no such directory"
                 continue
             }
+            [[ -L $IN_DIR ]] && {
+                # As per our design, after failover softlink /var/motr is
+                # created to points /var/motr{1-2}, and since our INPUT_DIR
+                # is globe pattern (/var/motr*) we end up collecting m0traces
+                # and cores twice unnecessary, hence skipped data collection
+                # if IN_DIR is a soft link.
+                continue
+            }
             export IN_DIR=$(readlink -f $IN_DIR)
 
             local label=$stage
@@ -122,7 +130,7 @@ main() {
 
     # Collects compressed core generated in /var/crash and /var/log/crash
     for IN_DIR in  ${CORE_DIRS[@]}; do 
-	[[ -d $IN_DIR ]] || {
+        [[ -d $IN_DIR ]] || {
                 warn "$IN_DIR: no such directory"
                 continue
         }
@@ -202,6 +210,7 @@ probes() {
         ##   which calls m0t1fs code. Will be re-enabled when m0t1fs locking
         ##   is fixed.
         # 'df -h -x m0t1fs -x nfs'
+        'df -h'
         'lspci'
         'gcc --version'
         'ip addr'
@@ -681,12 +690,10 @@ m0traces() {
 
     (cd "$IN_DIR"
      {
-         find . -type f -name m0trace.\* | last_modified "${M0TRACES_MAX:-}"
+         find . -maxdepth 1 -type f -name m0trace.\* | last_modified "${M0TRACES_MAX:-}"
          find . -maxdepth 1 -type d -name m0d-\* | while read dir; do
              find $dir -type f -name m0trace.\* |
                  last_modified "${M0TRACES_M0D_MAX:-}"
-         find ./hax -maxdepth 1 -type f -name m0trace.\* |
-             last_modified "${M0TRACES_MAX:-}"
          done
      } | cut -c3- | sort -u | while read path; do
          _tracedump $path $outdir
@@ -797,7 +804,8 @@ exit
 ### ---------- ------- ----------------------------------------------------
 ### 2020-10-05 0.52    Removed halon related things since we are not using
 ###                    it.Removed collection of kernel buffer because we lack
-###                    of debugfs support.
+###                    of debugfs support.Removed collection of m0traces of
+###                    s3server and hax. Added 'df -h' to probe info. 
 ###
 ### 2020-10-02 0.51    Added /var/log/crash to CORE_DIRS list since on
 ###                    provisioner deployed setup, core would be in /var/log/crash
