EOS-23116 debugging m0reportbug error
It is created for testing purpose. No need to review.

Do not merge/land  this.
Currently in debug phase.

Signed-off-by: Rinku Kothiya <rinku.kothiya@seagate.com>

diff --git a/utils/m0reportbug b/utils/m0reportbug
--- a/utils/m0reportbug
+++ b/utils/m0reportbug
@@ -18,9 +18,13 @@
 # please email opensource@seagate.com or cortx-questions@seagate.com.
 #
 
-set -eu
+set -o errtrace
+set -o functrace
+
+#set -eu
 # set -x
 export PS4='+ [${FUNCNAME[0]:+${FUNCNAME[0]}:}${LINENO}] '
+trap 'echo "ERR trap called in ${FUNCNAME-main context}. As $BASH_COMMAND failed with error code $?"' ERR
 
 ### ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ### When modifying this script, please increment VERSION and add new
@@ -117,7 +121,7 @@ main() {
             section "[$label]"
             local t=$(date +%s)
             $stage
-            echo "OK$(_time $t)" >&2
+            echo "OKAY1$(_time $t)" >&2
 
             # Stages that don't use $IN_DIR (e.g., probes, systemd_journal)
             # should only be executed once.
@@ -126,6 +130,7 @@ main() {
     done >>$REPORT
 
     # Collects compressed core generated in /var/crash and /var/log/crash
+    echo "rinkudebug0 array contents are   ${CORE_DIRS[@]}  (_time $t)" >&2
     for IN_DIR in  ${CORE_DIRS[@]}; do 
         [[ -d $IN_DIR ]] || {
                 warn "$IN_DIR: no such directory"
@@ -136,9 +141,17 @@ main() {
         section "[$label]" >>$REPORT
         local t=$(date +%s)
         backtraces_cores >>$REPORT
-        echo "OK$(_time $t)" >&2
+        echo "OKAY2$(_time $t)" >&2
+        echo "rinkudebug0.1 iteration $IN_DIR" >&2
     done
 
+    echo "rinkudebug 1 now lets find $ $LIVE_CORE_DIR (_time $t)" >&2
+    echo "ls -l $LIVE_CORE_DIR" >&2
+    du_output=$(ls -l $LIVE_CORE_DIR)
+    echo "$du_output" >&2
+    echo "du -sh $LIVE_CORE_DIR" >&2
+    du_output=`du -sh "$LIVE_CORE_DIR" 2>&1` 
+    echo "$du_output" >&2
     # Collects live/compressed core generated in /var/crash
     if [ -d $LIVE_CORE_DIR ]; then
         IN_DIR=${LIVE_CORE_DIR}
@@ -149,29 +162,36 @@ main() {
         backtraces_cores >>$REPORT
         # Remove live-cores generated in LIVE_CORE_DIR
         rm -rf $LIVE_CORE_DIR/core-live.*
-        echo "OK$(_time $t)" >&2
+        echo "OKAY3$(_time $t)" >&2
+    echo "rinkudebug 2 " >&2
     else
+    echo "rinkudebug 3 " >&2
         warn "$LIVE_CORE_DIR: no such directory"
     fi
 
+    echo "rinkudebug 4 " >&2
     # Collects traces for beck run
     if [ -d $RECOVERY_SCRIPT_DIR ]; then
+    echo "rinkudebug 5 " >&2
         IN_DIR=${RECOVERY_SCRIPT_DIR}
         local label="m0traces $IN_DIR"
         echo -n "$label... " >&2
         section "[$label]" >>$REPORT
         local t=$(date +%s)
         m0traces >>$REPORT
-        echo "OK$(_time $t)" >&2
+        echo "OKAY4$(_time $t)" >&2
     else
+    echo "rinkudebug 6 " >&2
         warn "$RECOVERY_SCRIPT_DIR: no such directory"
     fi
 
+    echo "rinkudebug 7 " >&2
     # Collects traces of m0d process(confd, ios) only
     M0TR_M0D_TRACE_DIR=$(cat /etc/sysconfig/motr  | grep "^MOTR_M0D_TRACE_DIR" | cut -d '=' -f2)
     M0D_TRACE_DIR="${M0TR_M0D_TRACE_DIR%\'}"
     M0D_TRACE_DIR="${M0D_TRACE_DIR#\'}"
 
+    echo "rinkudebug 8 " >&2
     if [[ -d "$M0D_TRACE_DIR" ]]; then
         IN_DIR=${M0D_TRACE_DIR}
         local label="m0traces $IN_DIR"
@@ -179,8 +199,10 @@ main() {
         section "[$label]" >>$REPORT
         local t=$(date +%s)
         m0traces >>$REPORT
-        echo "OK$(_time $t)" >&2
+        echo "OKAY5$(_time $t)" >&2
+    echo "rinkudebug 9 " >&2
     else
+    echo "rinkudebug 10 " >&2
         warn "$M0TR_M0D_TRACE_DIR: no such directory"
     fi
 
@@ -189,6 +211,7 @@ main() {
     ADDB_DIR="${ADDB_RECORD_DIR%\'}"
     ADDB_DIR="${ADDB_DIR#\'}"
 
+    echo "rinkudebug 11 " >&2
     if [[ -d "$ADDB_DIR" ]]; then
         IN_DIR=${ADDB_DIR}
         local label="addb-files $IN_DIR"
@@ -196,15 +219,18 @@ main() {
         section "[$label]" >>$REPORT
         local t=$(date +%s)
         addb-files >>$REPORT
-        echo "OK$(_time $t)" >&2
+        echo "OKAY6$(_time $t)" >&2
+    echo "rinkudebug 12 " >&2
     else
         warn "$ADDB_DIR: no such directory"
+    echo "rinkudebug 13 " >&2
     fi
 
     popd >/dev/null
     # Collect rpm-update-logs
     if [ -f /var/log/motr-rpm-conf-update.log ]; then
         cp -pv /var/log/motr-rpm-conf-update.log $OUT_DATA_DIR/
+    echo "rinkudebug 14 " >&2
     fi
 
     tar --remove-files -cJf $OUT_DATA_DIR{.tar.xz,}
@@ -215,11 +241,14 @@ main() {
             files+=":$t.tar.xz"
         fi
     done
+    echo "rinkudebug 15 " >&2
     if echo $files | grep -q :; then
         echo 'Please attach these files to the bug report:' >&2
         echo $files | sed -e 's/^/  /' -e 's/:/\n  /g' >&2
+    echo "rinkudebug 16 " >&2
     else
         echo "Please attach $files to the bug report." >&2
+    echo "rinkudebug 17 " >&2
     fi
 }
 
@@ -592,9 +621,11 @@ _coredump() {
 }
 
 backtraces_cores() {
+    echo "rinkudebug 1.0 " >&2
     local outdir=$START_DIR/$OUT_CORES_DIR
     local core
     local prog
+    echo "rinkudebug 1.1 " >&2
 
     ## Print backtraces.
     if [ -n "$GDB" ]; then
@@ -608,6 +639,7 @@ backtraces_cores() {
             fi
         done
     fi
+    echo "rinkudebug 1.3 " >&2
 
     ## Pack core dumps.
     section core dumps $IN_DIR
@@ -618,6 +650,7 @@ backtraces_cores() {
              _coredump $core $outdir
          fi
      done)
+    echo "rinkudebug 1.4 " >&2
 
     # Copy the readily available compressed core.*.xz
     [[ -d $outdir/$IN_DIR ]] || mkdir -p "$outdir/$IN_DIR"
@@ -629,6 +662,7 @@ backtraces_cores() {
             cp $core $outdir/$IN_DIR/
         fi
     done
+    echo "rinkudebug 1.5 " >&2
 
     if [ -d $outdir ] && ! rmdir $outdir 2>/dev/null; then
         ## Core dumps were collected. We need to collect binaries.
